source 'http://rubygems.org'

gem 'rails', '2.3.8', :require => nil
gem 'paperclip', '2.3.3'
gem 'will_paginate', '2.3.14'
gem 'authlogic', '2.1.5'
gem 'mysql', '2.8.1'
gem 'googlecalendar'
gem 'nokogiri'

group :development do
	gem 'sqlite3-ruby', '1.2.5', :require => 'sqlite3'
	gem 'ffaker', '0.4.0'
end
